// ─── Tipos ───────────────────────────────────────────────────────────────────

export type MovieAnalysis = { contexto: string; recepcion: string; legado: string }
export type SeriesAnalysis = { contexto: string; recepcion: string; legado: string }
export type GameAnalysis   = { propuesta: string; recepcion: string; legado: string }

// ─── Películas ────────────────────────────────────────────────────────────────

export const movieAnalysis: Record<string, MovieAnalysis> = {
  'spider-man-2002': {
    contexto: 'En 2002, llevar a Spider-Man al cine en live-action era una apuesta arriesgada que pocos estudios se habían atrevido a acometer con presupuesto AAA. Sam Raimi no solo lo consiguió, sino que capturó el espíritu del cómic clásico de Stan Lee y Steve Ditko con una mezcla de romanticismo, humor y acción que resultó absolutamente refrescante para el género.',
    recepcion: 'La película fue un fenómeno cultural inmediato: largas colas en cines, merchandising agotado y una recaudación histórica que sorprendió a la propia Sony. La crítica destacó la química entre Tobey Maguire y Kirsten Dunst, y el Duende Verde de Willem Dafoe se convirtió al instante en uno de los grandes villanos del cine de superhéroes.',
    legado: 'Sin Spider-Man (2002) el cine de superhéroes moderno no existiría tal como lo conocemos. Demostró que estos personajes podían funcionar con profundidad emocional y no solo como espectáculo, abriendo la puerta a todo lo que vendría después. El icónico beso boca abajo con MJ sigue siendo una de las imágenes más reconocibles de la historia del género.',
  },
  'spider-man-2-2004': {
    contexto: 'Considerada por muchos críticos como la secuela perfecta, Spider-Man 2 profundiza en la dualidad de Peter Parker con una honestidad emocional poco habitual en el cine de superhéroes. Raimi eleva el listón al centrarse tanto en el conflicto interno del protagonista —¿merece el hombre detrás de la máscara tener una vida propia?— como en la amenaza externa del Doctor Octopus.',
    recepcion: 'Ganó el Oscar a Mejores Efectos Visuales y cosechó críticas entusiastas por su equilibrio entre acción y drama. La secuencia del tren fue elegida durante años como una de las mejores escenas de acción del género. Alfred Molina dio vida a un villano complejo y trágico que todavía hoy se menciona como referencia.',
    legado: 'Spider-Man 2 estableció el estándar para las secuelas de superhéroes: más oscura, más madura y más valiente narrativamente que su predecesora. Su influencia directa se puede rastrear en películas como The Dark Knight o Logan, que adoptaron el mismo enfoque de explorar el coste humano de ser un héroe.',
  },
  'spider-man-3-2007': {
    contexto: 'Spider-Man 3 es el ejemplo más citado de lo que ocurre cuando la ambición supera la capacidad narrativa. Sony presionó para incluir a Venom contra los deseos del propio Raimi, y el resultado fue una película con tres villanos, tres arcos argumentales y demasiado poco tiempo para desarrollar ninguno con la profundidad que merecía.',
    recepcion: 'A pesar de las críticas divididas, recaudó más que sus predecesoras en taquilla mundial. El público quedó atrapado entre el espectáculo visual —notablemente superior— y la inconsistencia dramática. El Peter Parker "emo" con flequillo se convirtió en un meme cultural que persiste hasta hoy, con cariño y perplejidad a partes iguales.',
    legado: 'Paradójicamente, Spider-Man 3 terminó siendo una película más recordada que ignorada. Sus fallos se estudian en escuelas de guion como caso práctico de sobreproducción, pero también despertó en toda una generación la curiosidad por Venom, personaje que décadas después sigue siendo uno de los más populares del universo arácnido.',
  },
  'the-amazing-spider-man-2012': {
    contexto: 'Cinco años después del cierre de la trilogía de Raimi, Sony apostó por un reboot con Andrew Garfield y una estética más oscura e indie. Marc Webb, conocido por (500) Days of Summer, trajo una sensibilidad romántica poco habitual al género y revisó el origen de Peter Parker con un tono más adolescente y contemporáneo.',
    recepcion: 'La química entre Andrew Garfield y Emma Stone fue unánimemente elogiada —y acabó siendo real fuera de las cámaras— pero la historia se resintió de comparaciones inevitables con la versión de Raimi. El Lagarto como villano no convenció del todo a la crítica, aunque los efectos y el ritmo de la acción se consideraron un avance técnico notable.',
    legado: 'The Amazing Spider-Man es hoy más valorada de lo que fue en su estreno. La interpretación de Garfield ganó admiradores con el tiempo, y su aparición en No Way Home provocó una reivindicación masiva de esta etapa. La película demostró que Spider-Man podía funcionar con diferentes personalidades y tones, enriqueciendo el concepto del multiverso antes de que este existiera en pantalla.',
  },
  'the-amazing-spider-man-2-el-poder-de-electro-2014': {
    contexto: 'Sony intentó replicar el modelo del MCU construyendo un universo propio con The Amazing Spider-Man 2, introduciendo semillas para el Sinister Six y varios villanos en paralelo. El resultado fue una película atrapada entre sus propias ambiciones de franquicia y la necesidad de contar una historia coherente en dos horas.',
    recepcion: 'El Electro de Jamie Foxx y el Duende Verde de Dane DeHaan generaron opiniones encontradas, pero la secuencia de la muerte de Gwen Stacy impactó profundamente al público y es considerada uno de los momentos más desgarradores del cine de superhéroes. Una escena que pocos esperaban y que demostró que la película tenía agallas cuando se lo proponía.',
    legado: 'El fracaso relativo de esta entrega llevó al acuerdo entre Sony y Marvel Studios que devolvió a Spider-Man al MCU. Sin esta película y sus problemas, posiblemente no existirían Homecoming ni No Way Home. La muerte de Gwen Stacy, fiel al cómic, sigue siendo para muchos fans el momento más emotivo de toda la saga cinematográfica.',
  },
  'spider-man-homecoming-2017': {
    contexto: 'La integración de Spider-Man en el MCU fue un ejercicio de reinvención magistral. Jon Watts optó por una película de instituto clásica, con claras influencias de John Hughes, donde Peter Parker es ante todo un adolescente que intenta compaginar el cole, los amigos y ser Avenger. Tony Stark como mentor añadió una capa emocional nueva al personaje.',
    recepcion: 'La crítica recibió Homecoming con entusiasmo: el tono ligero, el humor inteligente y la frescura de Tom Holland funcionaron a la perfección. Michael Keaton compone uno de los mejores villanos del MCU con un Buitre que tiene motivaciones creíbles y clase trabajadora, algo inusual en el género. La vuelta a casa de Spider-Man a Marvel fue celebrada por los fans como un regalo largamente esperado.',
    legado: 'Homecoming redefinió qué puede ser una película de Spider-Man: no hace falta repetir el origen ni la tragedia. Basta con mostrar la energía y la ingenuidad de un chico de 15 años que quiere hacer el bien. Este enfoque influyó directamente en las secuelas y estableció a Tom Holland como el Spider-Man del MCU para una generación entera.',
  },
  'spider-man-un-nuevo-universo-2018': {
    contexto: 'Into the Spider-Verse es la película de animación más revolucionaria de la última década. Sus directores desarrollaron técnicas visuales completamente nuevas —puntos de Ben-Day, líneas de acción, perspectivas imposibles— para crear algo que parece un cómic en movimiento. Miles Morales llega finalmente al cine con la grandeza que el personaje merece.',
    recepcion: 'Oscar a Mejor Película de Animación, críticas prácticamente perfectas y una respuesta del público que la convirtió en fenómeno cultural. La multiverse de Spider-Man —Spider-Gwen, Spider-Man Noir, Spider-Ham, Peni Parker— resultó fresca y divertida sin sacrificar la emoción del arco principal de Miles. Es la película que demostró que la animación adulta puede competir con el live-action en ambición narrativa.',
    legado: 'Into the Spider-Verse cambió la animación cinematográfica para siempre. Su estética ha sido imitada en videojuegos, series y cómics, y su forma de contar el multiverso influyó directamente en la dirección artística del MCU. Miles Morales pasó de ser un personaje relativamente de nicho a convertirse en uno de los Spider-Man más queridos de todos los tiempos.',
  },
  'spider-man-lejos-de-casa-2019': {
    contexto: 'Far From Home tenía la difícil misión de ser el epílogo emocional de Avengers: Endgame y al mismo tiempo contar su propia historia. La decisión de llevar a Peter Parker a Europa funcionó como metáfora de un chico que necesita alejarse de Nueva York —y de la sombra de Tony Stark— para encontrar su propio camino.',
    recepcion: 'Jake Gyllenhaal como Mysterio es uno de los mayores aciertos de casting del MCU: el personaje pasa del héroe inspirador al villano más elaborado de la trilogía de Tom Holland. El giro de su identidad real fue genuinamente sorprendente, y las secuencias de ilusiones son visualmente impresionantes. El clímax post-créditos, con la exposición pública de Peter Parker, dejó al público con la mandíbula abierta.',
    legado: 'Far From Home es la película puente perfecta de la trilogía: consolida al personaje, introduce consecuencias narrativas que No Way Home resuelve brillantemente, y ofrece suficiente espectáculo propio para funcionar de manera independiente. La exposición de la identidad de Peter cambió las reglas del juego y preparó el terreno para la película más ambiciosa de la saga.',
  },
  'spider-man-no-way-home-2021': {
    contexto: 'No Way Home es la carta de amor definitiva a los fans de Spider-Man en el cine. La confluencia de tres actores que interpretaron al personaje en una misma película —algo que parecía imposible hace apenas cinco años— fue el evento cinematográfico más esperado de su generación. El multiverso dejó de ser un recurso narrativo para convertirse en el corazón emocional de la historia.',
    recepcion: 'El regreso de Tobey Maguire y Andrew Garfield provocó reacciones de auténtica euforia en los cines del mundo. La escena en que Garfield atrapa a MJ —la redención que su versión de Spider-Man nunca tuvo— emocionó hasta las lágrimas a una generación de fans. Con más de 1.900 millones de dólares de recaudación, es una de las películas más taquilleras de la historia.',
    legado: 'No Way Home cierra una era y abre otra simultáneamente. Es la primera película de Spider-Man que funciona como celebración del legado completo del personaje en el cine, reconociendo que todas las versiones son válidas y tienen su valor. El sacrificio de Peter en el acto final —borrar su identidad de la memoria del mundo— es la versión más adulta y emotiva del "gran poder, gran responsabilidad".',
  },
  'spider-man-cruzando-el-multiverso-2023': {
    contexto: 'Across the Spider-Verse supera a su predecesora en prácticamente todo: en ambición visual, en profundidad narrativa y en la complejidad de los dilemas morales que plantea. Cada universo tiene su propio estilo de animación y su propia paleta cromática, un logro técnico sin precedentes que convierte cada fotograma en una obra de arte.',
    recepcion: 'La crítica fue unánime en considerarla una obra maestra de la animación moderna. El arco de Miles Morales alcanza una madurez sorprendente: un chico que descubre que su existencia es un error en el canon del multiverso y que debe decidir si acepta su destino o lucha contra él. El cliffhanger final dejó al público en estado de shock y con ganas desesperadas de la tercera parte.',
    legado: 'Across the Spider-Verse ha redefinido una vez más los límites de la animación y la narración visual. Su influencia en la industria tardará años en calibrarse. Miles Morales es hoy, para millones de jóvenes de todo el mundo, su Spider-Man: el que les representa, el que les dice que también ellos pueden ser el héroe de su propia historia.',
  },
  'venom-2018': {
    contexto: 'Venom supuso el primer gran intento de Sony de construir un universo Spider-Man propio sin Spider-Man. La apuesta de tomar a uno de los villanos más populares del cómic y darle su propia película de antihéroe generó expectación y escepticismo a partes iguales. Tom Hardy asumió el doble reto de interpretar tanto a Eddie Brock como al simbionte.',
    recepcion: 'La crítica la recibió con frialdad, señalando la falta de un arco villain creíble y el tono irregular. Sin embargo, el público la adoró: la química cómica entre Eddie y Venom —dos personalidades en un mismo cuerpo— resultó absurdamente entretenida. La película recaudó más de 850 millones de dólares, demostrando que el personaje tiene tirón propio sin necesitar al trepamuros.',
    legado: 'Venom abrió la puerta al Sony Spider-Man Universe y probó que los antihéroes pueden funcionar en el cine sin estar atados a la narrativa heroica tradicional. Su tono de buddy-comedy sobrenatural, aunque divisivo, encontró su público y sentó las bases de una franquicia que continúa expandiéndose. La frase "somos Venom" se convirtió al instante en icónica.',
  },
  'venom-habra-matanza-2021': {
    contexto: 'La secuela de Venom apostó por reducir el tiempo de metraje y maximizar el caos. Andy Serkis tomó las riendas con una película más pequeña en escala pero más afilada en su propuesta de comedia de terror. La llegada de Carnage —el simbionte más peligroso del universo Marvel— prometía la confrontación que los fans de los cómics llevaban décadas esperando.',
    recepcion: 'Woody Harrelson como Cletus Kasady y Carnage fue bien recibido por los fans del cómic, aunque la crítica volvió a señalar el ritmo irregular y la subutilización del villano. La escena post-créditos, en la que Eddie Brock y Venom son transportados brevemente al universo del MCU y ven a Peter Parker en televisión, provocó una reacción viral que superó con mucho a la propia película.',
    legado: 'Let There Be Carnage es recordada principalmente por su post-créditos, que conectó el universo de Venom con el MCU de manera inesperada. Sin ese giro, la película habría quedado como una secuela competente pero menor. Con él, se convirtió en un eslabón narrativo importante en el rompecabezas del Spider-Verse cinematográfico.',
  },
  'morbius-2022': {
    contexto: 'Morbius llegó precedida de una larga campaña de marketing que prometía un villano-antihéroe de enorme potencial. Jared Leto asumió el papel del vampiro viviente con la intención de replicar el éxito de Venom, pero la recepción fue un aviso de que no todos los personajes secundarios del universo arácnido funcionan igual de bien como protagonistas.',
    recepcion: "La crítica fue devastadora y el público tardó poco en hacerse eco de ese veredicto. Los memes generados por la película —especialmente el \"It's Morbin' Time\"— se convirtieron en un fenómeno de internet que, paradójicamente, le dio a Morbius más visibilidad que cualquier campaña de marketing convencional. Sony relanzó la película en cines por la popularidad de los memes, con resultados decepcionantes.",
    legado: 'Morbius pasará a la historia como un ejemplo de lo que ocurre cuando se prioriza la construcción de un universo compartido sobre la calidad de la historia individual. Su fracaso contribuyó a replantear la estrategia de Sony con sus personajes de Spider-Man y abrió el debate sobre si todos los villanos pueden sostenerse solos una película entera.',
  },
  'kraven-the-hunter-2024': {
    contexto: 'Kraven the Hunter intentó ofrecer una versión oscura y visceral de uno de los antagonistas más clásicos del universo arácnido. Aaron Taylor-Johnson asumió el papel de Sergei Kravinoff con una historia de origen que explora la relación del personaje con la naturaleza, la depredación y la búsqueda de un código ético propio, alejado de la visión de simple villano.',
    recepcion: 'La película llegó en un momento complicado para el Sony Spider-Man Universe, con el público y la crítica en guardia tras los resultados de Morbius y la irregular Let There Be Carnage. Aunque la actuación de Taylor-Johnson fue reconocida como un punto fuerte, la historia no logró convencer a quienes esperaban una propuesta más audaz y diferenciadora.',
    legado: 'Kraven the Hunter cierra una etapa del Sony Spider-Man Universe marcada por resultados desiguales. Su legado está aún por escribirse, pero representa el esfuerzo de la franquicia por explorar el lado más oscuro y complejo de los personajes secundarios del universo arácnido, una apuesta que tendrá que refinarse en futuras entregas.',
  },
  'madame-web-2024': {
    contexto: 'Madame Web exploró un territorio completamente nuevo dentro del universo de Spider-Man: una protagonista femenina con poderes proféticos y una narrativa centrada en la conexión entre tres futuras Spider-Women. Dakota Johnson asumió el papel de Cassandra Webb, un personaje prácticamente desconocido fuera de los lectores de cómic más habituales.',
    recepcion: "La película se convirtió en blanco de críticas feroces que señalaron problemas en el guion, el ritmo y la coherencia narrativa. La frase \"He was in the Amazon with my mom\" se viralizó como símbolo de diálogo poco natural. Sin embargo, algunas voces señalaron que la propuesta original de una película de superhéroes femenina con tono de thriller merecía una ejecución más cuidada.",
    legado: 'Madame Web es probablemente la película más discutida del universo arácnido por razones que poco tienen que ver con sus virtudes. Su impacto en la industria está más relacionado con el debate sobre cómo desarrollar personajes femeninos de superhéroes que con su aportación narrativa. El futuro del Sony Spider-Man Universe dependerá en buena medida de las lecciones aprendidas de esta etapa.',
  },
}

// ─── Series ───────────────────────────────────────────────────────────────────

export const seriesAnalysis: Record<string, SeriesAnalysis> = {
  'spider-man': {
    contexto: 'La serie de 1967 fue la primera adaptación animada de Spider-Man para televisión y un producto absolutamente pionero. Con animación limitada y presupuestos modestos, el equipo logró capturar la esencia del cómic de Stan Lee y Steve Ditko: un chico corriente con poderes extraordinarios que lucha contra el crimen en Nueva York. Su música es tan icónica que décadas después sigue siendo la melodía más reconocible del personaje.',
    recepcion: 'En su momento fue un éxito rotundo entre el público infantil americano y contribuyó de manera decisiva a convertir a Spider-Man en un nombre conocido a nivel mundial, más allá de los lectores de cómic. Con el tiempo, la serie ha ganado un aura de nostalgia irresistible, y sus fotogramas reutilizados —famosos entre los fans— se han convertido en memes clásicos de la cultura de internet.',
    legado: 'Sin esta serie, Spider-Man no habría alcanzado la popularidad masiva que le permitió sobrevivir como franquicia durante décadas. Su sintonía, su estética y sus villanos icónicos forman parte del ADN cultural del personaje. Todo lo que vino después, desde las películas de Raimi hasta el MCU, tiene una deuda enorme con esta producción de 1967.',
  },
  'spider-man-y-sus-sorprendentes-amigos': {
    contexto: 'A principios de los 80, Marvel y NBC apostaron por una fórmula de equipo que ya había funcionado con Los Vengadores: Peter Parker no está solo, sino acompañado de Firestar e Iceman. La serie introdujo a Firestar como personaje original creado expresamente para la animación, y su tono de aventuras compartidas resultó refrescante frente al Spider-Man solitario de la serie del 67.',
    recepcion: 'Fue uno de los dibujos animados más vistos de su época en la franja matinal del sábado, generando merchandising y atrayendo a una nueva generación de fans de los cómics Marvel. La dinámica de los tres protagonistas funcionó mejor de lo esperado y la serie se recuerda con mucho cariño por quienes crecieron con ella en los primeros años 80.',
    legado: 'La serie demostró que Spider-Man podía compartir protagonismo sin perder su identidad y abrió la puerta a versiones de equipo del personaje que luego aparecerían en cómics y otras adaptaciones. Firestar, su mayor aportación original, acabó integrándose en el canon de los cómics de Marvel, lo que dice mucho del impacto cultural de la producción.',
  },
  'spiderman': {
    contexto: 'La serie de los 90 de Fox Kids es para muchos la versión definitiva de Spider-Man en animación. Con una narrativa ambiciosa que adaptó con fidelidad arcos clásicos como The Alien Costume Saga, el surgimiento de Venom y Carnage, o el crossover con los X-Men, la serie elevó el listón de lo que podía contar un dibujo animado de superhéroes. El Peter Parker veinteañero, con problemas reales y dilemas morales, conectó con una audiencia mucho más amplia que la infantil.',
    recepcion: 'Fue un fenómeno televisivo que definió la infancia de toda una generación. La crítica especializada la señala como una de las mejores series animadas de superhéroes jamás producidas, y los fans la sitúan sistemáticamente entre las dos o tres mejores adaptaciones de Spider-Man en cualquier medio. La actuación de Christopher Daniel Barnes como Peter Parker/Spider-Man es considerada referencial.',
    legado: 'Esta serie es responsable de que millones de personas en todo el mundo se convirtieran en fans de Spider-Man. Sus versiones de Venom, el Duende Verde, el Doctor Octopus o Mary Jane Watson siguen siendo las más queridas para buena parte de los fans de 30-40 años. Su influencia en el MCU es innegable: varios diseños y decisiones narrativas de las películas de Tom Holland beben directamente de esta producción.',
  },
  'spider-man-the-new-animated-series': {
    contexto: 'Producida por MTV y con animación CGI en 2003, esta serie intentó llevar a Spider-Man a un público joven adulto con un tono más oscuro y maduro. Tobey Maguire prestó su voz al personaje, aprovechando el tirón de la primera película de Raimi. La estética era radicalmente distinta a cualquier adaptación anterior: personajes angulosos, paleta de colores más sombría y tramas con contenido más adulto.',
    recepcion: 'La recepción fue desigual. Los fans más jóvenes la adoptaron bien, pero los veteranos encontraron la animación fría y los personajes difíciles de reconocer. Su breve duración —una sola temporada de 13 episodios— impidió que desarrollara todo su potencial, aunque algunos episodios son genuinamente memorables por su atrevimiento narrativo.',
    legado: 'Aunque fue una serie breve y hoy algo olvidada, representó un experimento valioso: demostró que Spider-Man podía funcionar en animación CGI y con un tono adulto mucho antes de que Into the Spider-Verse lo elevara a obra maestra. Su existencia abrió conversaciones sobre cómo modernizar el personaje para audiencias más maduras.',
  },
  'el-espectacular-spiderman': {
    contexto: 'The Spectacular Spider-Man de 2008 es probablemente la serie animada mejor escrita de la historia del personaje. Greg Weisman, creador de Gargoyles, combinó lo mejor de las diferentes etapas del cómic —el instituto, la universidad, los romances, los villanos clásicos— en una narrativa cohesionada y planificada desde el principio. La animación de estilo retro-moderno y la caracterización de los personajes son sobresalientes.',
    recepcion: 'La crítica la recibió con elogios casi unánimes y los fans la situaron rápidamente entre las mejores adaptaciones del personaje. La cancelación tras dos temporadas por problemas de derechos entre Marvel y Sony fue un golpe devastador para la comunidad fan, que lleva años reclamando su continuación o un final digno. Es, para muchos, la serie cancelada más injustamente de la historia de la animación.',
    legado: 'The Spectacular Spider-Man es la referencia que toda nueva adaptación animada intenta igualar. Su enfoque en Peter Parker adolescente, sus villanos con motivaciones comprensibles y su respeto por el material original influyeron directamente en el Spider-Man de Homecoming. Greg Weisman ha confirmado en múltiples ocasiones que tenía planificadas al menos seis temporadas: lo que pudo haber sido sigue siendo motivo de debate entre los fans.',
  },
  'ultimate-spider-man': {
    contexto: 'Ultimate Spider-Man de 2012 fue una apuesta distinta y conscientemente diferente: en lugar de buscar la fidelidad narrativa, priorizó la acción, el humor y la conexión con el MCU en plena expansión. Peter Parker forma parte de los S.H.I.E.L.D. Junior Spideys, un equipo de jóvenes héroes, y la serie incorpora cameos constantes de personajes del universo Marvel. Los gags de pantalla partida y las rupturas de la cuarta pared marcaron un estilo propio.',
    recepcion: 'Generó opiniones muy divididas: quienes la juzgaron como sustituta de Spectacular Spider-Man la encontraron superficial e irritante. Quienes la tomaron por lo que era —una serie de aventuras ligera orientada al público más joven— la disfrutaron sin complejos durante sus cuatro temporadas. Fue un éxito comercial innegable y mantuvo a Spider-Man muy presente en la televisión durante años.',
    legado: 'Aunque no alcanzó el nivel artístico de Spectacular, Ultimate Spider-Man cumplió su función: mantener vivo el interés por el personaje durante la gestación del Spider-Man del MCU y presentar a personajes como Miles Morales o Spider-Gwen a una audiencia joven antes de que llegaran al cine. Su legado es más comercial que artístico, pero no por ello menos real.',
  },
  'marvel-spider-man': {
    contexto: "Marvel's Spider-Man de 2017 llegó con la misión de acompañar el Spider-Man del MCU y ofrecer una versión animada moderna del personaje. Con un Peter Parker más joven, estudiante en el instituto Midtown, la serie recuperó el tono más íntimo y centrado en el colegio que Homecoming había reivindicado en el cine. La animación fue un paso adelante en calidad respecto a Ultimate Spider-Man.",
    recepcion: 'Fue bien recibida por los fans más jóvenes y por quienes buscaban una serie animada accesible y fiel al espíritu del MCU. Los fans más veteranos la encontraron correcta pero sin la ambición narrativa de Spectacular. Sus tres temporadas —la última titulada Maximum Venom— exploraron el universo de los simbiontes con resultados desiguales.',
    legado: 'La serie consolidó la versión MCU de Peter Parker en el imaginario colectivo más allá del cine y demostró que la animación y el live-action pueden coexistir y complementarse narrando historias distintas del mismo personaje. Fue el puente animado entre el Peter Parker de Tom Holland y las generaciones más jóvenes de fans.',
  },
  'tu-amigo-y-vecino-spider-man': {
    contexto: 'Tu amigo y vecino Spider-Man llega en 2025 a Disney+ como la primera serie animada de Spider-Man producida directamente dentro del MCU, con conexiones narrativas directas con las películas de Tom Holland. La producción apuesta por una animación de estilo comic-book y un tono que equilibra la acción del MCU con las aventuras cotidianas de un Peter Parker adolescente en Nueva York.',
    recepcion: 'Su estreno generó gran expectación entre los fans del MCU y de la animación de superhéroes, ansiosos por ver cómo encajaría en la continuidad establecida por las películas. La propuesta de una serie canónica dentro del MCU —algo sin precedentes para el personaje— la convierte en un experimento narrativo de primer orden cuya valoración definitiva llegará con el tiempo.',
    legado: 'Es demasiado pronto para calibrar su legado, pero su posición como primera serie animada canon del MCU la convierte ya en un hito histórico para el personaje. Si logra conectar con la audiencia y aportar historias relevantes dentro de la continuidad Marvel, podría redefinir el papel de la animación en el ecosistema del universo cinematográfico.',
  },
  'el-regreso-de-spiderman': {
    contexto: 'La serie animada de 1981 producida por Marvel Productions para ABC llegó como una segunda oportunidad para el Spider-Man televisivo, actualizando la estética de la serie del 67 con valores de producción notablemente superiores. Peter Parker regresó como un trepamuros más ágil y expresivo, con historias autoconclusivas que abordaban villanos clásicos del cómic en un formato accesible para el público familiar de los primeros 80.',
    recepcion: 'Fue recibida con buena acogida entre el público infantil de su época, consolidando a Spider-Man como una presencia fija en la parrilla animada del sábado por la mañana. Aunque no alcanzó el impacto cultural de la serie del 67, cumplió su función de mantener al personaje vigente en el imaginario popular durante una etapa de transición para Marvel en televisión.',
    legado: 'La serie de 1981 es hoy una producción poco recordada fuera de los fans más completistas, pero representó un eslabón necesario en la cadena de adaptaciones animadas del personaje. Mantuvo a Spider-Man en la televisión entre la era clásica del 67 y el boom de mediados de los 80, preparando el terreno para las ambiciosas producciones que vendrían después.',
  },
  'las-incre-bles-aventuras-de-spiderman': {
    contexto: 'Spider-Man Unlimited llegó en 1999 con una propuesta radicalmente diferente a todo lo anterior: Peter Parker viaja a Counter-Earth, un planeta paralelo donde los simbiontes dominan y la humanidad vive bajo opresión. La serie apostó por una estética futurista y oscura, alejada del Nueva York clásico, con un traje rediseñado y una narrativa de ciencia ficción distópica que sorprendió tanto a fans como a críticos.',
    recepcion: 'La propuesta fue recibida con curiosidad pero también con perplejidad. Quienes esperaban al Spider-Man de siempre encontraron una serie casi irreconocible en su ambientación, aunque la calidad de la animación y el atrevimiento narrativo ganaron admiradores. La cancelación prematura tras trece episodios —sin llegar a concluir su arco— dejó la historia sin resolución, frustrando a los fans que habían apostado por ella.',
    legado: 'Spider-Man Unlimited es hoy reivindicada como una de las series más valientes y originales del personaje: la única que se atrevió a sacarlo completamente de su contexto habitual y llevarlo a un universo de ciencia ficción pura. Su cancelación abrupta la convierte en otra historia de potencial no realizado, pero su existencia demuestra que Spider-Man puede funcionar en géneros y mundos completamente inesperados.',
  },
  'spidey-y-su-superequipo': {
    contexto: 'Spidey y su Superequipo llegó en 2021 a Disney+ como la primera serie animada de Spider-Man pensada específicamente para el público preescolar, con un Spidey muy joven acompañado de Ghost-Spider y Spin —la versión infantil de Miles Morales— formando un trío de héroes de barrio. La producción apuesta por una animación colorida y expresiva, historias breves autoconclusivas y valores de amistad y trabajo en equipo por encima de la acción.',
    recepcion: 'Fue recibida positivamente por padres y educadores como una introducción ideal al universo de Spider-Man para los más pequeños. La inclusión de Miles Morales como Spin desde el inicio fue celebrada como un paso importante en la representación, y la dinámica de los tres protagonistas funcionó bien para su público objetivo. Los fans adultos la adoptaron con afecto, reconociendo su propósito y valorando la ternura de la propuesta.',
    legado: 'Spidey y su Superequipo ocupa un lugar único en la historia del personaje: es la puerta de entrada al universo arácnido para toda una generación de niños que se acercan a Spider-Man antes de saber leer. Su importancia no es artística sino generacional: está construyendo la próxima oleada de fans del trepamuros desde la infancia, con una diversidad de protagonistas que refleja el mundo real de sus espectadores.',
  },
  'spiderman-toei-1978': {
    contexto: 'La versión japonesa de Spider-Man producida por Toei Company entre 1978 y 1979 es una de las adaptaciones más extraordinarias y desconcertantes del personaje: un motorista llamado Takuya Yamashiro recibe los poderes del trepamuros de un alienígena y combate al villano Professor Monster con la ayuda de un robot gigante llamado Leopardon. Marvel y Toei firmaron un acuerdo de intercambio de licencias que dio también origen a la franquicia Super Sentai, precursora de Power Rangers.',
    recepcion: 'En Japón fue un éxito de audiencia que cumplió su función como tokusatsu de acción semanal para el público infantil. Fuera de Japón permaneció prácticamente desconocida durante décadas, hasta que Marvel puso los episodios disponibles en su plataforma y la serie ganó una comunidad de fans internacionales fascinados por su peculiaridad. Su popularidad actual como objeto de culto supera con creces la que tuvo en su emisión original.',
    legado: 'La serie tokusatsu de Toei es hoy un fenómeno de culto que fascinó tanto a los propios creadores de Marvel que incluyeron a Takuya Yamashiro como uno de los Spider-Men del evento cómico Spider-Verse. Su influencia indirecta en la cultura popular es enorme: el mecanismo de robots gigantes que introdujo en el universo Spider-Man derivó directamente en Super Sentai y, por extensión, en Power Rangers, una de las franquicias infantiles más longevas de la historia.',
  },
  'spider-noir': {
    contexto: 'Spider-Noir es una de las propuestas más arriesgadas y originales del universo arácnido en televisión: una serie live-action en blanco y negro ambientada en el Nueva York de los años 30, con Nicolas Cage —quien ya prestó voz al personaje en Into the Spider-Verse— como Gideon Stacy, padre de Gwen. El tono de noir policiaco y la ambientación de época la alejan radicalmente de cualquier adaptación anterior.',
    recepcion: 'La sola premisa generó enorme interés entre los fans del cine negro y del Spider-Verse. La participación de Nicolas Cage dotó al proyecto de una credibilidad actoral y una identidad distintiva que muy pocas producciones de superhéroes han logrado desde el principio. Su recepción definitiva está aún por escribirse, siendo una producción de 2026.',
    legado: 'Spider-Noir representa la dirección más audaz que cualquier adaptación del universo arácnido ha tomado jamás: apostar por el género negro clásico, la ambientación histórica y el blanco y negro como elección artística. Si funciona, abrirá la puerta a versiones del personaje en géneros y épocas completamente inesperadas, expandiendo el concepto del Spider-Verse más allá de lo imaginado.',
  },
}

// ─── Videojuegos ──────────────────────────────────────────────────────────────

export const gameAnalysis: Record<string, GameAnalysis> = {
  'spider-man-2000-2000': {
    propuesta: 'El Spider-Man de Neversoft para PlayStation fue una revolución en su momento: por primera vez los jugadores podían moverse libremente por entornos tridimensionales como el trepamuros, escalando paredes, lanzando telarañas y combatiendo desde cualquier ángulo. La variedad de trajes desbloqueables y los diálogos con voces originales del cast de la serie animada de los 90 lo convirtieron en un regalo para los fans.',
    recepcion: 'Fue un éxito de crítica y ventas que demostró que Spider-Man podía ser protagonista de un gran juego en 3D. Los medios especializados destacaron la libertad de movimiento, el humor del guion y la cantidad de contenido extra. Para muchos jugadores de aquella generación fue su primera experiencia seria con el personaje en videojuegos.',
    legado: 'Spider-Man (2000) estableció la plantilla que todos los juegos posteriores del personaje intentaron seguir o superar. Su sistema de balanceo, su enfoque en la exploración vertical y su respeto por el material de origen siguen siendo referencias citadas cuando se habla de la historia de los juegos del trepamuros.',
  },
  'spider-man-2-enter-electro-2001': {
    propuesta: 'La secuela directa del Spider-Man de Neversoft mantuvo la fórmula del original y añadió a Electro como villano principal. El juego expandió las mecánicas de juego con nuevas habilidades y entornos, aunque seguía limitado por las capacidades de PlayStation. La historia, escrita expresamente para el videojuego, ofrecía una aventura original independiente de cualquier película o cómic concreto.',
    recepcion: 'Recibió críticas más discretas que su predecesor, señalándose que no aportaba suficientes novedades para justificar plenamente una secuela. Aun así, los fans del primero encontraron en él una continuación sólida y entretenida. Electro, históricamente difícil de trasladar a otros medios, resultó ser un villano efectivo en el contexto del juego.',
    legado: 'Enter Electro es hoy un título algo olvidado dentro del catálogo Spider-Man, eclipsado por el impacto del original y la llegada de Spider-Man 2 de Treyarch en 2004. Sin embargo, representa el cierre de una etapa y el epílogo de la era Neversoft con el personaje, mereciendo su lugar en la historia de los juegos del trepamuros.',
  },
  'spider-man-and-venom-maximum-carnage-1994': {
    propuesta: "Maximum Carnage es un beat 'em up de desplazamiento lateral basado en el arco de cómic homónimo, uno de los más oscuros y violentos de la historia del personaje. La posibilidad de jugar en cooperativo tanto con Spider-Man como con Venom fue un añadido que los fans adoraron. El cartucho rojo de SNES se convirtió en uno de los más reconocibles de la generación.",
    recepcion: "Su recepción fue positiva entre los fans del cómic que pudieron reconocer los guiños y la fidelidad al material original. La crítica generalista lo calificó como un beat 'em up competente pero sin grandes innovaciones respecto al género. La posibilidad de jugar con Venom como protagonista fue unánimemente celebrada como el mayor acierto del juego.",
    legado: 'Maximum Carnage es hoy un objeto de culto entre coleccionistas, especialmente la versión en cartucho rojo de SNES. Fue uno de los primeros juegos en trasladar un arco argumental específico de los cómics con notable fidelidad, sentando un precedente para las adaptaciones directas de historias del universo Marvel.',
  },
  'spider-man-mysterio-s-menace-2001': {
    propuesta: "Mysterio's Menace fue el primer juego de Spider-Man diseñado específicamente para Game Boy Advance, aprovechando las capacidades del hardware portátil para ofrecer una experiencia 2D de acción y plataformas. La mecánica de balanceo adaptada al formato horizontal y los enfrentamientos contra villanos clásicos como Mysterio, el Hombre de Arena y el Buitre definieron el ritmo del juego.",
    recepcion: 'Fue bien recibido como uno de los mejores juegos de superhéroes disponibles en GBA en su momento de lanzamiento. La crítica destacó la calidad de los gráficos para el hardware portátil y la variedad de situaciones jugables. Para los fans que no podían acceder a las consolas de sobremesa, fue una alternativa más que digna.',
    legado: 'Aunque limitado al contexto del hardware portátil de su época, Mysterio\'s Menace demostró que Spider-Man podía funcionar igualmente bien en formato 2D clásico que en los entornos 3D de PlayStation. Es un título querido por quienes crecieron con GBA y buscaban aventuras del trepamuros fuera del salón.',
  },
  'spider-man-web-of-shadows-2008': {
    propuesta: 'Web of Shadows apostó por un sistema de combate inusualmente profundo para un juego de superhéroes: la posibilidad de combinar ataques del traje rojo con los del traje de simbionte en tiempo real, y las decisiones morales que afectaban el desarrollo de la historia, le dieron una personalidad propia. El sistema de alianzas con otros héroes y villanos añadía capas estratégicas poco habituales en el género.',
    recepcion: 'La crítica valoró positivamente la innovación en el combate y las múltiples opciones narrativas, aunque señaló problemas técnicos y una ciudad abierta menos convincente que la de Spider-Man 2 de Treyarch. Los fans del personaje lo consideran un título injustamente infravalorado, con algunas de las mecánicas de combate más satisfactorias de toda la saga.',
    legado: 'Web of Shadows es hoy reivindicado por una comunidad de fans que lamenta que su propuesta de combate y narración moral nunca fuera continuada. El juego anticipó ideas que el género de los superhéroes en videojuegos tardaría años en retomar, y su exploración del simbionte como elemento jugable sigue siendo única en la historia del personaje.',
  },
  'ultimate-spider-man-2005': {
    propuesta: 'Ultimate Spider-Man de Treyarch fue el primer juego que utilizó cell-shading para replicar fielmente el estilo visual del cómic de Brian Michael Bendis y Mark Bagley. La posibilidad de jugar como Venom con mecánicas completamente distintas —devorar enemigos para recuperar salud, destruir entornos— añadió una dimensión nueva a la experiencia. La ciudad abierta de Nueva York compartida entre ambos personajes generaba situaciones únicas.',
    recepcion: 'La crítica y los fans lo recibieron con entusiasmo, destacando especialmente la fidelidad visual y el atrevimiento de incluir a Venom como protagonista jugable con su propio arco narrativo. Se considera uno de los mejores juegos del personaje de la era PlayStation 2, y muchos lo sitúan por delante del Spider-Man 2 de Treyarch en términos de diseño artístico.',
    legado: 'Ultimate Spider-Man demostró que la estética cel-shaded era la forma ideal de trasladar el cómic al videojuego, una lección que Into the Spider-Verse aplicaría décadas después en el cine. Su representación de Venom como figura trágica influyó en cómo el personaje fue tratado en medios posteriores.',
  },
  'marvel-s-spider-man-2018': {
    propuesta: 'El Spider-Man de Insomniac Games para PS4 redefinió lo que un juego de superhéroes podía ser. Su sistema de balanceo, el más fluido y satisfactorio jamás diseñado para el personaje, convierte el simple acto de moverse por Nueva York en un placer. La historia, que presenta a un Peter Parker de 23 años ya experimentado como héroe, tiene la madurez narrativa de una producción cinematográfica de primer nivel.',
    recepcion: 'Con metacrítica superior a 87, fue aclamado como uno de los mejores juegos del año y uno de los mejores de superhéroes de la historia. Las ventas superaron con creces las expectativas de Sony, convirtiéndolo en uno de los exclusivos de PS4 más vendidos. La interpretación de Yuri Lowenthal como Peter Parker fue universalmente elogiada.',
    legado: "Marvel's Spider-Man (2018) es el estándar contra el que todos los juegos de superhéroes son medidos desde su lanzamiento. Demostró que el género podía competir en ambición narrativa y técnica con las mejores producciones del medio. Su impacto en la cultura popular fue tal que influyó en el diseño visual de producciones posteriores del universo Marvel.",
  },
  'marvel-s-spider-man-remastered-2020': {
    propuesta: 'La versión remasterizada del Spider-Man de 2018 llegó a PS5 y PC con mejoras técnicas sustanciales: ray tracing, tiempos de carga casi inexistentes, 60 fps estables y el rediseño del rostro de Peter Parker para aproximarlo al modelo de Miles Morales. Incluye además los tres DLC de The City That Never Sleeps, ofreciendo la experiencia completa del juego original en un único paquete.',
    recepcion: 'Fue bien recibida como la versión definitiva del juego, aunque la polémica del rediseño facial de Peter Parker generó debate intenso en la comunidad. Los nuevos jugadores en PS5 y PC la adoptaron como punto de entrada a la saga Insomniac, y la versión de PC abrió el juego a una base de usuarios mucho más amplia a nivel mundial.',
    legado: 'El Remastered consolidó el Spider-Man de Insomniac como franquicia de primer nivel en el ecosistema PlayStation y demostró el potencial de PS5 para reimaginar experiencias de la generación anterior. La llegada a PC supuso además el inicio de la política de Sony de llevar sus exclusivos al ordenador.',
  },
  'marvel-s-spider-man-miles-morales-2020': {
    propuesta: 'Miles Morales es a la vez una secuela y una historia de origen: el juego presenta a Miles como Spider-Man de pleno derecho mientras Peter Parker está de viaje. Sus poderes de bioeléctricidad y camuflaje añaden una dimensión completamente nueva al sistema de combate y las mecánicas de sigilo. La historia, centrada en la comunidad latina de Harlem y la familia de Miles, tiene una resonancia emocional que el juego original no alcanzó.',
    recepcion: 'Recibió críticas entusiastas que lo situaron a la altura del original pese a su menor duración. La representación de Miles como héroe latino, la banda sonora con hip-hop y la ambientación navideña de Nueva York crearon una identidad visual y sonora única en el género. Se convirtió en juego de lanzamiento de PS5 y en uno de los argumentos más sólidos para adquirir la consola.',
    legado: 'Miles Morales demostró que Spider-Man podía ser mucho más que Peter Parker y que la diversidad en los protagonistas no solo es posible sino que enriquece la experiencia. El juego reforzó el amor del público por Miles iniciado por Into the Spider-Verse y estableció al personaje como uno de los héroes más queridos de la cultura pop contemporánea.',
  },
  'marvel-s-spider-man-2-2023': {
    propuesta: 'Spider-Man 2 de Insomniac es la apuesta más ambiciosa de la saga: dos Spider-Men jugables —Peter y Miles— en una Nueva York ampliada que incluye Queens y Brooklyn, con el simbionte Venom como eje narrativo central. La historia explora qué ocurre cuando el traje negro corrompe lentamente a Peter, ofreciendo la representación más oscura y compleja del personaje en la historia de los videojuegos.',
    recepcion: 'Superó las expectativas en términos técnicos y narrativos, con metacrítica por encima de 90. Las ventas en el primer fin de semana batieron todos los récords de la saga. La actuación de Tony Todd como Venom fue especialmente destacada por la crítica. La posibilidad de cambiar entre Peter y Miles en tiempo real en mundo abierto fue uno de los logros técnicos más celebrados.',
    legado: "Marvel's Spider-Man 2 consolida a Insomniac como el estudio de referencia para los juegos de superhéroes y establece el universo Insomniac de Spider-Man como una de las franquicias más valiosas del medio. Su representación de Venom como figura trágica es considerada la mejor de la historia del personaje en cualquier medio interactivo.",
  },
  'marvel-s-spider-man-2-pc-port-2025': {
    propuesta: 'El port de PC de Marvel\'s Spider-Man 2 llegó en 2024 llevando la experiencia completa de la saga Insomniac a los jugadores de ordenador. Con soporte para ray tracing avanzado, resoluciones ultra-wide y opciones de personalización gráfica extensas, la versión PC ofreció la experiencia visual más completa del juego hasta la fecha, además de compatibilidad con teclado y ratón y una amplia gama de mandos.',
    recepcion: 'El lanzamiento estuvo marcado por problemas técnicos en los primeros días que generaron críticas negativas en Steam, un patrón ya visto con puertos anteriores de Sony. Sin embargo, tras las actualizaciones iniciales, la comunidad PC adoptó el juego con entusiasmo, valorando especialmente las mejoras visuales sobre la versión de consola.',
    legado: 'El port PC de Spider-Man 2 completa la presencia de la trilogía de Insomniac en ordenadores, ampliando enormemente la base de jugadores que pueden acceder a esta saga. Confirma la estrategia de Sony de llevar gradualmente sus grandes exclusivos al PC y sitúa el universo Insomniac de Spider-Man como franquicia verdaderamente multiplataforma.',
  },
  'the-amazing-spider-man-vs-the-kingpin-1990': {
    propuesta: 'The Amazing Spider-Man vs. The Kingpin fue uno de los primeros juegos del personaje en ofrecer una experiencia de acción y plataformas en Sega Genesis con un nivel de detalle notable para su época. La mecánica central —recorrer los pisos de un rascacielos para desactivar una bomba nuclear antes de que explote— añadía una urgencia que pocos juegos de superhéroes de la época habían planteado. Las versiones de Sega CD incluyeron además voces digitalizadas y secuencias animadas inéditas.',
    recepcion: 'Fue bien recibido entre los usuarios de Mega Drive y se consideró uno de los mejores juegos de superhéroes disponibles en el sistema. La crítica especializada destacó la variedad de situaciones jugables y la fidelidad al universo del cómic. La versión de Sega CD, con su contenido adicional, fue considerada la edición definitiva y un argumento sólido para el periférico.',
    legado: 'The Amazing Spider-Man vs. The Kingpin es hoy una pieza de coleccionista apreciada por los fans de los juegos retro del trepamuros. Representó uno de los primeros intentos serios de trasladar la experiencia de Spider-Man a los 16 bits con ambición narrativa, y su inclusión del Kingpin como antagonista central lo convierte en un título singular dentro del catálogo del personaje en videojuegos.',
  },
  'spider-man-2-the-game-2004': {
    propuesta: 'El Spider-Man 2 de Treyarch, basado en la película de Sam Raimi, fue una revolución en el género de los juegos de mundo abierto: por primera vez era posible balancearse por un Manhattan completamente abierto con una física del movimiento que simulaba de verdad el peso y la inercia del trepamuros. El sistema de balanceo —que requería atar la telaraña a edificios reales— cambió para siempre las expectativas de los fans sobre cómo debía moverse Spider-Man en un videojuego.',
    recepcion: 'Fue un éxito de crítica y ventas que superó con creces a su predecesor. Los medios especializados lo señalaron como uno de los mejores juegos de superhéroes de su generación, destacando especialmente la libertad de movimiento y la fidelidad a la sensación de ser Spider-Man. Para millones de jugadores de PS2 y Xbox, fue la experiencia definitiva del personaje hasta la llegada del Insomniac de 2018.',
    legado: 'Spider-Man 2 (2004) es el título que definió el estándar del balanceo en los juegos del personaje durante más de una década. Su influencia directa se puede rastrear en todos los juegos posteriores de Spider-Man, y el propio Insomniac Games citó sus mecánicas de movimiento como referencia durante el desarrollo del Spider-Man de 2018. Es, para una generación entera de jugadores, el juego de Spider-Man de su infancia.',
  },
  'spider-man-shattered-dimensions-2010': {
    propuesta: 'Shattered Dimensions apostó por una propuesta única en la historia de los juegos del personaje: cuatro Spider-Men simultáneos —Amazing, Noir, 2099 y Ultimate con el traje simbionte— cada uno con su propio estilo visual, mecánicas de juego y tono narrativo. El Spider-Man Noir en blanco y negro con sigilo obligatorio, el Spider-Man 2099 con acrobacias futuristas en caída libre y el Spider-Man Ultimate con poderes de simbionte desbocados ofrecían experiencias genuinamente distintas dentro de un mismo juego.',
    recepcion: 'La crítica valoró positivamente la ambición del concepto y la variedad de las cuatro propuestas jugables, aunque señaló cierta irregularidad en la calidad entre los diferentes universos. Los fans del cómic encontraron en las versiones Noir y 2099 versiones sorprendentemente fieles al espíritu del material original. El juego vendió bien y demostró que el concepto del multiverso tenía enorme potencial en los videojuegos.',
    legado: 'Shattered Dimensions anticipó varios años antes que el cine y los cómics el interés masivo por el concepto del Spider-Verse y los universos alternativos. Su exploración de Spider-Man Noir y Spider-Man 2099 como protagonistas jugables influyó en la popularización de estas versiones del personaje, que luego encontrarían nueva vida en Into the Spider-Verse y Across the Spider-Verse.',
  },
  'marvel-s-spider-man-the-heist-2018': {
    propuesta: 'El primer capítulo de la expansión The City That Never Sleeps centra su historia en el regreso de Black Cat al universo de Peter Parker. El DLC añade nuevas misiones principales, misiones secundarias de la Gata Negra y varios trajes nuevos, extendiendo la narrativa del juego base con una trama de robo y traición que explora la complicada relación entre Peter y Felicia Hardy con más profundidad de la que la historia principal permitió.',
    recepcion: 'Fue bien recibido como un complemento de calidad al juego base, con una narrativa más íntima y personal que la épica del juego principal. La presencia de Black Cat como figura central generó interés entre los fans del personaje, aunque la duración del capítulo fue señalada como más breve de lo esperado para el precio del pase de temporada.',
    legado: 'The Heist estableció el tono y el formato de los DLC de la saga Insomniac: historias secundarias que expanden el universo del juego con personajes adicionales y nuevas capas narrativas. La representación de Black Cat en este capítulo es considerada una de las mejores del personaje en los videojuegos, rescatando su complejidad moral y su relación ambigua con Spider-Man.',
  },
  'marvel-s-spider-man-silver-lining-2018': {
    propuesta: 'Silver Lining cierra la trilogía de DLC de The City That Never Sleeps con un capítulo que recoge los hilos argumentales de los dos anteriores y los lleva a su conclusión. La historia involucra a Silver Sable, cuya muerte aparente al final del juego base se revisita, y añade nuevas facciones de enemigos y misiones que amplían el mapa de actividades de la ciudad. Es el capítulo más largo y completo de los tres.',
    recepcion: 'Fue recibido como el mejor de los tres DLC, valorado por su mayor duración, la resolución satisfactoria de los arcos narrativos iniciados en los capítulos anteriores y la calidad del enfrentamiento final. Los fans agradecieron el cierre que el capítulo ofrecía para varios personajes secundarios del juego base, y la inclusión de Silver Sable como aliada fue bien acogida.',
    legado: 'Silver Lining completa la experiencia del Spider-Man de 2018 de manera coherente, añadiendo capas a un universo que el juego base ya había construido con solidez. Junto con los otros dos capítulos, demuestra que los DLC de la saga Insomniac no son simples rellenos sino expansiones narrativas genuinas. Su contenido está incluido en el Remastered de PS5 y PC como parte de la edición definitiva.',
  },
  'marvel-s-spider-man-the-city-that-never-sleeps-2018': {
    propuesta: 'The City That Never Sleeps es el pase de temporada completo del Spider-Man de Insomniac de 2018, compuesto por tres capítulos descargables: The Heist, Turf Wars y Silver Lining. Juntos añaden varias horas de historia adicional centrada en Black Cat, el regreso de Hammerhead y la resolución de la trama de Silver Sable, ampliando el universo del juego con nuevos personajes, trajes y zonas de actividad en el mapa de Nueva York.',
    recepcion: 'El pase de temporada completo fue recibido positivamente como una extensión de calidad del juego base. Si bien cada capítulo individualmente fue señalado como breve, los tres juntos ofrecían una cantidad de contenido proporcional a su precio y con una narrativa cohesionada que funcionaba mejor en conjunto. Los fans del juego encontraron en ellos la excusa perfecta para volver a Nueva York.',
    legado: 'The City That Never Sleeps demostró que el universo Insomniac de Spider-Man tenía material más que suficiente para expandirse más allá del juego principal. Su contenido está hoy integrado en el Marvel\'s Spider-Man Remastered como parte de la edición definitiva, garantizando que las historias adicionales lleguen a todos los nuevos jugadores de la saga.',
  },
}
